In [3]:
import numpy as np
n1 = np.array([[2,3, 4],[5,6,7]])
n2 = np.array([[4,5,6],[1,2,3]])

<h1>Basics</h1>

In [30]:
#Operations
ad = n1 + 4
mul = n1 * 4
dot = n1.dot(n2)
power = n1 ** 2
cos  = np.cos(n1)
sin = np.sin(n1)
print(ad)
print(mul)
print(dot)
print(power)
print(cos)
print(sin)

[6 7 8]
[ 8 12 16]
47
[ 4  9 16]
[-0.41614684 -0.9899925  -0.65364362]
[ 0.90929743  0.14112001 -0.7568025 ]


In [4]:
#dimensions of numpy array
n1.ndim

1

In [5]:
#get shape
n1.shape #(no.of elements in a row or cols , no.of rows)

(3,)

In [6]:
n1.dtype

dtype('int32')

In [7]:
#Get Each Items size
n1.itemsize

4

In [8]:
n1.size * n1.itemsize #total size

12

In [9]:
#also total size
n1.nbytes

12

<h1>Accessing and Changing specific elements</h1>

In [10]:
a = np.array([[12,23,34,45,56,67,78],[98,87,65,54,43,32,21]])
print(a)

[[12 23 34 45 56 67 78]
 [98 87 65 54 43 32 21]]


In [11]:
#[row,col]
s = a[1,4]
print(s)

43


In [12]:
s = int(s)
print(type(s))

<class 'int'>


In [13]:
#specific columns of a row
d = a[0,1:5]
print(d)

[23 34 45 56]


In [14]:
# specific cols of all rows
f = a[:,2:6]
print(f)

[[34 45 56 67]
 [65 54 43 32]]


<h3> Changing Elements</h3>

In [15]:
#changing
a[0,3] = 44
print(a)
#changing full col
a[:,2] = 11
print(a)
#changing full coll with another list
c = [2,3]
a[:,5] = c
print(a)
#and so can be done with a row

[[12 23 34 44 56 67 78]
 [98 87 65 54 43 32 21]]
[[12 23 11 44 56 67 78]
 [98 87 11 54 43 32 21]]
[[12 23 11 44 56  2 78]
 [98 87 11 54 43  3 21]]


<h3> Initializing Different types of Array </h3>

In [16]:
#all zeros
z = np.zeros((2,3), dtype = 'int16') #default datatype = float
#also np.ones()
#also any other number
v = np.full((3,3), 44)
print(z)
print(z.dtype)
print(v)

[[0 0 0]
 [0 0 0]]
int16
[[44 44 44]
 [44 44 44]
 [44 44 44]]


In [17]:
#of the the same dimensions
b = np.full_like(f,8)# np.full_like(other_object, initialized_by)
#also 
m = np.full(f.shape, 8)
print(b)
print(m)

[[8 8 8 8]
 [8 8 8 8]]
[[8 8 8 8]
 [8 8 8 8]]


<b>random decimal numbers</b>

In [18]:
r = np.random.rand(2,5)
print(r)

[[0.54522618 0.90443032 0.45278552 0.42439658 0.69950159]
 [0.9169317  0.43433494 0.09347542 0.9587228  0.0508468 ]]


<b>random integers </b>

In [19]:
i = np.random.randint(-2,9, size=(4,3)) # randint(starting_point , ending_point_exclusive ,  size = (row, cols))
print(i)

[[ 3 -1 -1]
 [ 2 -1 -2]
 [ 6 -1  5]
 [ 8  6  0]]


In [20]:
np.identity(4, dtype="int16")

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int16)

problem create the following martrix <br>
[1 1 1 1 1 <br>
 1 0 0 0 1 <br>
 1 0 9 0 1 <br>
 1 0 0 0 1 <br>
 1 1 1 1 1] <br>

In [21]:
ones = np.ones((5,5), dtype='int16')
ones[1:4, 1:4] = 0
ones[2,2] = 9
print(ones)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


<b> Copying One array into another array </b>

In [26]:
u = np.array([1,2,3,4])
w = u.copy() #important
w[0] = 45
print(u)

[1 2 3 4]


## Linear Algebra

In [42]:
m1 = np.ones((2,3), dtype="int16")
print(m1)

m2 = np.full((3,2), 2)
print(m2)

matmul = np.matmul(m1, m2)
print(matmul)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]
[[6 6]
 [6 6]]


In [54]:
#find determinant
# matrix = np.full((4,4) , 2)
# matrix[:,2] = 3
# matrix[1,:] = 5
# matrix[0,:] = 7
matrix = np.array([[2,4,6], [2,4,1], [5,3,1]])
print(matrix)
determ = np.linalg.det(matrix)
print(determ)

[[2 4 6]
 [2 4 1]
 [5 3 1]]
-69.99999999999996


In [55]:
#for more operations visit 
# https://docs.scipy.org/doc/numpy/reference/rouines.linalg.html

## Statistics

In [57]:
stats = np.random.randint(1,9, size=(3,4))
print(stats)

[[4 6 5 8]
 [1 3 6 1]
 [8 1 7 2]]


In [66]:
mini = np.min(stats, axis=0) #axis = 0 for cols and 1 for rows
print("minmum from cols : \t", mini)
maxi = np.max(stats, axis=1) # rows or vertically
print("maximum from rows : \t", maxi)

minmum from cols : 	 [1 1 5 1]
maximum from rows : 	 [8 6 8]


In [67]:
np.sum(stats)

52

## Reorganising Arrays

In [72]:
before = np.array([[1,2,3,4],[4,5,6,7]])
print(before)

after = before.reshape(4, 2)
print(after)

[[1 2 3 4]
 [4 5 6 7]]
[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [77]:
a1 = np.array([2,3,4,5])
a2 = np.array([9,8,7,6])
arr = np.vstack([a1,a2,a1,a1,a2])
print(arr)

[[2 3 4 5]
 [9 8 7 6]
 [2 3 4 5]
 [2 3 4 5]
 [9 8 7 6]]


In [124]:
b1 = np.ones((1,4), dtype="int8")
b2 = np.full((2,4), 2, dtype="int8")
hstk = np.vstack([b1,b2,b1,b2]) # no.of cols of every array should be the same
print(hstk)
#and so np.hstack

[[1 1 1 1]
 [2 2 2 2]
 [2 2 2 2]
 [1 1 1 1]
 [2 2 2 2]
 [2 2 2 2]]


In [120]:
nparr1 = np.array([[2,3,2,3],[8,9,7,6]])
nparr2 = np.array([[5,4],[1,0]]) 
hstack = np.hstack([nparr1, nparr2]) # no.of rows of every array should be the same 
print(hstack)

[[2 3 2 3 5 4]
 [8 9 7 6 1 0]]


# Boolean Masking And Advance indexing

In [22]:
filedata = np.genfromtxt('data.txt', delimiter = ',', dtype='int16')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [23]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [24]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int16)

In [27]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [30]:
np.all(filedata > 50, axis=0) # all elements in the col are greater than 50

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [40]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [60]:
mat = np.array(range(30)) + 1
mat = mat.reshape((6,5))
print(mat)
inside = mat[2:4,:2]
print(inside)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[11 12]
 [16 17]]


In [63]:
mat[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [67]:
mat[[0,-2,-1],-2:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])